export { Layout } from './Layout/Layout';
export { EmptyLayout } from './Layout/EmptyLayout';
export { Home } from './Home/Home';
export { Test } from './Test/Test';
export { ArticleDetail } from './Article/ArticleDetail';
export { CreateArticle } from './Article/CreateArticle';
export { UpdateArticle } from './Article/UpdateArticle';
export { ArticlesByTags } from './Article/ArticlesByTags';
export { Register } from './Register/Register';
export { Login } from './Login/Login';
export { RecommendTags } from './Register/RecommendTags';
export { Profile } from './Profile/Profile';
export { SearchResult } from './Global/SearchResult';
export { Term } from './Legal/Term';
export { Error } from './Error/Error'
